# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-26 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('looking_for', models.TextField()),
                ('responsibilities', models.TextField()),
            ],
        ),
    ]
