# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-26 10:04
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180326_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='looking_for',
            field=tinymce.models.HTMLField(),
        ),
    ]
